CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name          VARCHAR(255) NOT NULL,
  email         VARCHAR(512) NOT NULL,
  CONSTRAINT    pk_user PRIMARY KEY (id),
  CONSTRAINT    UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name          VARCHAR(255) NOT NULL,
  description   VARCHAR(512) NOT NULL,
  available     BOOLEAN NOT NULL,
  owner_id      BIGINT NOT NULL,
  request_id    BIGINT NOT NULL,
  CONSTRAINT    pk_item PRIMARY KEY (id),
  CONSTRAINT    uq_owner_id UNIQUE (owner_id),
  FOREIGN KEY   (owner_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT     GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  END_DATE      timestamp(6) without time zone,
  START_DATE    timestamp(6) without time zone,
  item_id       bigint NOT NULL,
  booker_id     bigint NOT NULL,
  status        smallint,  
  CONSTRAINT    pk_booking PRIMARY KEY (id),
  FOREIGN KEY   (item_id) REFERENCES items(id),
  FOREIGN KEY   (booker_id) REFERENCES users(id)
);