name: API Tests

on:
  workflow_call:
    inputs:
      postgres-wait:
        type: boolean
        default: false
        description: 'Whether to wait for PostgreSQL to be ready'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for PostgreSQL
        if: inputs.postgres-wait
        run: |
          echo "Waiting for PostgreSQL to start..."
          for i in {1..10}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "PostgreSQL not ready yet. Attempt $i/10"
            sleep 2
          done

      # Your existing build and test steps
      - name: Build with Maven
        run: mvn clean package